### ISSUE TITLE
个人充值是可以的，支付没有问题，但是购物车下单支付就报错，接口404

### ISSUE THREAD

**Issue by longzb2008** [Dejavu-Tech/EP-WechatApp#4]
下单支付有问题
![CleanShot 2023-12-20 at 3  39 10@2x](https://github.com/Dejavu-Tech/EP-WechatApp/assets/16234591/21b49cba-a56c-43f7-ae50-f496ba2dc254)
![CleanShot 2023-12-20 at 3  38 58@2x](https://github.com/Dejavu-Tech/EP-WechatApp/assets/16234591/72dc50a2-6c3b-4dc4-9b5e-971b683bff0b)
![CleanShot 2023-12-20 at 3  40 46@2x](https://github.com/Dejavu-Tech/EP-WechatApp/assets/16234591/e587ba98-6a00-476d-86ad-da5b5d9e38db)
充值是OK的
![CleanShot 2023-12-20 at 3  40 20@2x](https://github.com/Dejavu-Tech/EP-WechatApp/assets/16234591/bee0d80e-e431-4e63-9336-925f1b43353b)

**Comment by zhrrobert** [comment]
请确认微信商户平台v2秘钥、证书正确并下载证书上传至后台，如有v3秘钥请关闭，详细错误在小程序vConsole支付日志里有

**Comment by longzb2008** [comment]
> 请确认微信商户平台v2秘钥、证书正确并下载证书上传至后台，如有v3秘钥请关闭，详细错误在小程序vConsole支付日志里有

V3是在商户这里关闭么
![Uploading CleanShot 2023-12-26 at 9 .51.17@2x.png…]()

**Comment by longzb2008** [comment]
> 请确认微信商户平台v2秘钥、证书正确并下载证书上传至后台，如有v3秘钥请关闭，详细错误在小程序vConsole支付日志里有

V3密钥关不了，怎么关闭啊

**Comment by zhrrobert** [comment]
> > 请确认微信商户平台v2秘钥、证书正确并下载证书上传至后台，如有v3秘钥请关闭，详细错误在小程序vConsole支付日志里有
> 
> V3密钥关不了，怎么关闭啊

V2秘钥生效48小时后才可关闭

**Comment by longzb2008** [comment]
![CleanShot 2024-01-13 at 7  25 26](https://github.com/Dejavu-Tech/EP-WechatApp/assets/16234591/c91e3251-87eb-4eae-ac83-9b99b358849f)

我换了个商户号，这里没有设置设置APIv3密钥，但还是支付失败，余额充值可以成功

**Comment by zhrrobert** [comment]
请注明小程序 vConsole 控制台支付日志

**Comment by longzb2008** [comment]
![CleanShot 2024-01-18 at 5  09 54](https://github.com/Dejavu-Tech/EP-WechatApp/assets/16234591/c9fdf549-8083-4778-a5b3-8e6bd2807360)
![CleanShot 2024-01-18 at 5  10 22](https://github.com/Dejavu-Tech/EP-WechatApp/assets/16234591/1b4c15f8-0066-4fcf-8cb5-5e1dbc2cae4a)

**Comment by longzb2008** [comment]
![CleanShot 2024-01-18 at 5  24 36](https://github.com/Dejavu-Tech/EP-WechatApp/assets/16234591/bfbc63fc-9bf3-43b4-92b7-1ea8c022ff63)

**Comment by zhrrobert** [comment]
请注明小程序 vConsole 控制台支付日志
