### ISSUE TITLE
新增商品流程不通，没有 门店添加 的入口

### ISSUE THREAD

**Issue by longzb2008** [Dejavu-Tech/EP-WechatApp#5]
添加商品流程步骤中，有一步是 到店核销 功能，没有门店添加的入口，其他的设置中，也缺少入口，比如 选择商户，运费模板
![CleanShot 2024-01-13 at 5  55 25](https://github.com/Dejavu-Tech/EP-WechatApp/assets/16234591/402210cf-5667-4495-a9bf-c9e2d708db4e)
![CleanShot 2024-01-13 at 6  00 20](https://github.com/Dejavu-Tech/EP-WechatApp/assets/16234591/03b37eff-5653-416a-817a-b0e9c374945a)

**Comment by zhrrobert** [comment]
商户、门店等为商用版功能
